applications:
- name: github-kl-mcp-server
  instances: 1
  memory: 256M
  buildpacks:
    - binary_buildpack
  health-check-type: process
  command: "./github-mcp-server http --port $PORT --gh-host https://github.com --toolsets context,orgs,repos,pull_requests"
  routes:
    - route: github-kl-mcp-server.apps.internal